define: &mono_0   "#23262e"
define: &mono_1   "#2f323c"
define: &mono_2   "#3a3e4b"
define: &mono_3   "#464959"
define: &mono_4   "#a0a1a7"
define: &mono_5   "#d5ced9"

define: &cyan     "#00e8c6"
define: &pink     "#ff00aa"
define: &purple   "#c74ded"
define: &orange   "#f39c12"
define: &yellow   "#ffe66d"
define: &hot_pink "#f92672"
define: &blue     "#7cb7ff"
define: &red      "#ee5d43"
define: &green    "#96e072"

gui:
  border: "rounded"
  nerdFontsVersion: "3"
  timeFormat: '02 Jan 06'
  shortTimeFormat: '15:04'
  theme:
    activeBorderColor:
      - *cyan
      - bold
    inactiveBorderColor:
      - *mono_3
    searchingActiveBorderColor:
      - *cyan
      - bold
    optionsTextColor:
      - *blue
    selectedLineBgColor:
      - *mono_2
    selectedRangeBgColor:
      - *mono_2
    cherryPickedCommitBgColor:
      - *cyan
    cherryPickedCommitFgColor:
      - *blue
    unstagedChangesColor:
      - *red
    defaultFgColor:
      - *mono_5

os:
  editPreset: 'nvim'
