name: macOS build

on:
  push:
    branches: [master, development]

  schedule:
    - cron: "0 3 * * *" # Runs every night at 03:00

jobs:
  flake:
    runs-on: macos-26

    steps:
      - uses: actions/checkout@v5

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16

      - name: Enable flakes
        run: |
          mkdir -p ~/.config/nix
          echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf

      - name: Flake check
        run: nix flake check

      - name: Build nix-darwin system
        run: nix build .#darwinConfigurations.Norberts-MacBook-Pro.system
